RSA-Factoring-Challenge

diff --git a/factors b/factors
--- a/factors
+++ b/factors
@@ -1,41 +1,24 @@
 #!/usr/bin/env bash
-# Calculate factors of numbers
+# Factorization Challenge
 
 calculate_factors() {
-    if [ $# -ne 3 ]; then
-        args=("$@")
-        count=0
-        product=1
-        for arg in "${args[@]}"; do
-            if [ $count -gt 1 ]; then
-                product=$(echo "$arg * $product" | bc)
-            fi
-            count=$((count + 1))
-        done
-    else
-        product=$3
-    fi
-
-    num1=$2
-    num_repr=$(echo "$1" | tr ':' '=')
-
-    result=$(echo "if ($product > $num1) 1 else 0" | bc)
-    if ((result == 1)); then
-        temp=$num1
-        num1=$product
-        product=$temp
-    fi
-
-    echo "$num_repr$num1*$product"
+    num=$1
+    factors=$(factor "$num" | cut -d ':' -f 2-)
+    echo "$num = $factors"
 }
 
 if [ $# -ne 1 ]; then
-    echo 'Usage: calculate_factors <file>'
+    echo 'Usage: script_name <file>'
     exit 1
 else
-    while read number; do
-        factorization=$(factor "$number")
-        calculate_factors $factorization
-    done < "$1"
-fi
+    input_file="$1"
 
+    if [ ! -f "$input_file" ]; then
+        echo "File not found: $input_file"
+        exit 1
+    fi
+
+    while read -r number; do
+        calculate_factors "$number"
+    done < "$input_file"
+fi
